# Generated by Django 5.1.1 on 2024-10-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApplication', '0004_alter_post_tags_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
