# Generated by Django 5.1.1 on 2024-10-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApplication', '0005_post_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_to_read',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
