# Generated by Django 5.1.1 on 2024-10-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApplication', '0006_post_time_to_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_intro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
