# Generated by Django 5.1.1 on 2024-10-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApplication', '0007_post_short_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_intro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
